env:
  global:
    - GO111MODULE=on
    - CC_TEST_REPORTER_ID=c74e6420edb325076ac85c9f2744d38aefdfcc30158a180bd2148a5d1fd24af2

dist: xenial
language: go
go:
  - 1.11.x
  - tip
before_install: sudo apt-get install -y jq
install: go mod vendor
script: |
  ls /usr/local/include
  go test -mod vendor -coverprofile=c.out -covermode=atomic

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
- ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT
